require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

# Rails and ActiveRecord autogenerate a lot of code that fails Rubocop
# (I find this mildly confusing/annoying). Also, there's no point in
# having Rubocop look at JavaScript, images, shell scripts, etc.
AllCops:
  EnabledByDefault: true
  Exclude:
    - db/**/*
    - bin/*
    - app/assets/**/*
    - coverage/**/*
    - docs/*
    - log/*
    - node_modules/**/*
    - public/**/*
    - tmp/**/*
    - tools/**/*
    - '**/vendor/**/*' # since we `bundle install --path vendor/bundle` on CI

# Spec files and the routes file are supposed to be one long block. Shush.
Metrics/BlockLength:
  Exclude:
    - Gemfile
    - spec/**/*.rb
    - config/routes.rb
    - config/environments/*
    - lib/tasks/*.rake

# This set of tests use IP addresses for good reasons
Style/IpAddresses:
  Exclude:
    - spec/features/ip_restrictions_spec.rb

# Whitespace Considered Helpful
Layout/ExtraSpacing:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/SpaceInsideParens:
  Enabled: false
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false
Layout/SpaceInsideReferenceBrackets:
  Enabled: false

# I'd rather use one style of regex everywhere, that is clearer for munging URLs
# as no need to escape '/': %r{/(path)/parts/} rather than /\/(path)\/parts\//
# Style/RegexpLiteral:
#  Enabled: false

# I have no idea what this is but it was annoying me.
Style/FrozenStringLiteralComment:
  Enabled: false

# ... nah
Bundler/GemComment:
  Enabled: false
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false
Lint/ConstantResolution:
  Enabled: false
Lint/NumberConversion:
  Enabled: false
Style/Copyright:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Style/InlineComment:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: false
Style/MissingElse:
  Enabled: false
Style/StringHashKeys:
  Enabled: false

# TODO: Fix this stuff
Layout/ArgumentAlignment:
  Enabled: false
Layout/ClosingParenthesisIndentation:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/FirstArgumentIndentation:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Naming/FileName:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/ImplicitRuntimeError:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Rails/SaveBang:
  Enabled: false
Rails/Validation:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/AnyInstance:
  Exclude:
    - 'spec/requests/items_spec.rb'
